//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlienRP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlienRP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ARPMessageBox_Cancel {
            get {
                return ResourceManager.GetString("ARPMessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ARPMessageBox_No {
            get {
                return ResourceManager.GetString("ARPMessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ARPMessageBox_OK {
            get {
                return ResourceManager.GetString("ARPMessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ARPMessageBox_Yes {
            get {
                return ResourceManager.GetString("ARPMessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap classical_back {
            get {
                object obj = ResourceManager.GetObject("classical_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap classical_text {
            get {
                object obj = ResourceManager.GetObject("classical_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap di_back {
            get {
                object obj = ResourceManager.GetObject("di_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap di_text {
            get {
                object obj = ResourceManager.GetObject("di_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down arrow.
        /// </summary>
        public static string HotkeyArrowDown {
            get {
                return ResourceManager.GetString("HotkeyArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow.
        /// </summary>
        public static string HotkeyArrowLeft {
            get {
                return ResourceManager.GetString("HotkeyArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow.
        /// </summary>
        public static string HotkeyArrowRight {
            get {
                return ResourceManager.GetString("HotkeyArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up arrow.
        /// </summary>
        public static string HotkeyArrowUp {
            get {
                return ResourceManager.GetString("HotkeyArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid button.
        /// </summary>
        public static string HotkeyNotValid {
            get {
                return ResourceManager.GetString("HotkeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start / Stop.
        /// </summary>
        public static string HotkeysControl_Action0 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        public static string HotkeysControl_Action1 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string HotkeysControl_Action2 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string HotkeysControl_Action3 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote UP.
        /// </summary>
        public static string HotkeysControl_Action4 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote DOWN.
        /// </summary>
        public static string HotkeysControl_Action5 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vote.
        /// </summary>
        public static string HotkeysControl_Action6 {
            get {
                return ResourceManager.GetString("HotkeysControl_Action6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string HotkeysControl_ActionTitle {
            get {
                return ResourceManager.GetString("HotkeysControl_ActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string HotkeysControl_GlobalTitle {
            get {
                return ResourceManager.GetString("HotkeysControl_GlobalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl + Shift).
        /// </summary>
        public static string HotkeysControl_GlobalTitle_comment {
            get {
                return ResourceManager.GetString("HotkeysControl_GlobalTitle_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальные.
        /// </summary>
        public static string HotkeysControl_LocalTitle {
            get {
                return ResourceManager.GetString("HotkeysControl_LocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string HotkeysControl_Title {
            get {
                return ResourceManager.GetString("HotkeysControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icomoon {
            get {
                object obj = ResourceManager.GetObject("icomoon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jazz_back {
            get {
                object obj = ResourceManager.GetObject("jazz_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jazz_text {
            get {
                object obj = ResourceManager.GetObject("jazz_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading channels....
        /// </summary>
        public static string LoadingControl_RadioChannels {
            get {
                return ResourceManager.GetString("LoadingControl_RadioChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic login.
        /// </summary>
        public static string LoginWindow_AutoLogin {
            get {
                return ResourceManager.GetString("LoginWindow_AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string LoginWindow_AutoLoginProcess {
            get {
                return ResourceManager.GetString("LoginWindow_AutoLoginProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string LoginWindow_EmailCaption {
            get {
                return ResourceManager.GetString("LoginWindow_EmailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field cannot be empty.
        /// </summary>
        public static string LoginWindow_EmailError1 {
            get {
                return ResourceManager.GetString("LoginWindow_EmailError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string LoginWindow_EmailError2 {
            get {
                return ResourceManager.GetString("LoginWindow_EmailError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the password recovery page on {0}.
        /// </summary>
        public static string LoginWindow_ForgotLink {
            get {
                return ResourceManager.GetString("LoginWindow_ForgotLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you forgot your password, go to the password recovery page.
        /// </summary>
        public static string LoginWindow_ForgotText {
            get {
                return ResourceManager.GetString("LoginWindow_ForgotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string LoginWindow_ForgotTitle {
            get {
                return ResourceManager.GetString("LoginWindow_ForgotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LoginWindow_FormTitle {
            get {
                return ResourceManager.GetString("LoginWindow_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginWindow_LoginButton {
            get {
                return ResourceManager.GetString("LoginWindow_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string LoginWindow_LoginPasswordError {
            get {
                return ResourceManager.GetString("LoginWindow_LoginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error. Check your connection and try again.
        /// </summary>
        public static string LoginWindow_NoInternet {
            get {
                return ResourceManager.GetString("LoginWindow_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a Premium Member.
        /// </summary>
        public static string LoginWindow_NotPremium {
            get {
                return ResourceManager.GetString("LoginWindow_NotPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string LoginWindow_PasswordCaption {
            get {
                return ResourceManager.GetString("LoginWindow_PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field cannot be empty.
        /// </summary>
        public static string LoginWindow_PasswordError {
            get {
                return ResourceManager.GetString("LoginWindow_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string LoginWindow_RememberMe {
            get {
                return ResourceManager.GetString("LoginWindow_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the account page page on {0}.
        /// </summary>
        public static string LoginWindow_SocialLink {
            get {
                return ResourceManager.GetString("LoginWindow_SocialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the same email address as for your social network account. You must specify the password on the account page.
        /// </summary>
        public static string LoginWindow_SocialText {
            get {
                return ResourceManager.GetString("LoginWindow_SocialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with FB or G+.
        /// </summary>
        public static string LoginWindow_SocialTitle {
            get {
                return ResourceManager.GetString("LoginWindow_SocialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string MainWindow_MenuChannels {
            get {
                return ResourceManager.GetString("MainWindow_MenuChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string MainWindow_MenuRadioStations {
            get {
                return ResourceManager.GetString("MainWindow_MenuRadioStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_MenuSettings {
            get {
                return ResourceManager.GetString("MainWindow_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a channel from the list below.
        /// </summary>
        public static string MainWindow_SelectChannel {
            get {
                return ResourceManager.GetString("MainWindow_SelectChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings.
        /// </summary>
        public static string MainWindow_SelectSettings {
            get {
                return ResourceManager.GetString("MainWindow_SelectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a station from the list below.
        /// </summary>
        public static string MainWindow_SelectStation {
            get {
                return ResourceManager.GetString("MainWindow_SelectStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSans_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSans_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error. Please try again later.
        /// </summary>
        public static string PlayerControl_BadRequestError {
            get {
                return ResourceManager.GetString("PlayerControl_BadRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering....
        /// </summary>
        public static string PlayerControl_Buffering {
            get {
                return ResourceManager.GetString("PlayerControl_Buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel not found. Reload channels list and try again.
        /// </summary>
        public static string PlayerControl_ChannelError {
            get {
                return ResourceManager.GetString("PlayerControl_ChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information about next track.
        /// </summary>
        public static string PlayerControl_GetNewTrack {
            get {
                return ResourceManager.GetString("PlayerControl_GetNewTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information about current track.
        /// </summary>
        public static string PlayerControl_GetTrack {
            get {
                return ResourceManager.GetString("PlayerControl_GetTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string PlayerControl_LogoutButton {
            get {
                return ResourceManager.GetString("PlayerControl_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error. Please re-login.
        /// </summary>
        public static string PlayerControl_MemberError {
            get {
                return ResourceManager.GetString("PlayerControl_MemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error. Check your connection and try again.
        /// </summary>
        public static string PlayerControl_NoInternet_Text {
            get {
                return ResourceManager.GetString("PlayerControl_NoInternet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string PlayerControl_Reconnect {
            get {
                return ResourceManager.GetString("PlayerControl_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string PlayerControl_ReloadChannelsButton {
            get {
                return ResourceManager.GetString("PlayerControl_ReloadChannelsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio stream error. Please try again later or select another channel.
        /// </summary>
        public static string PlayerControl_StreamlistError {
            get {
                return ResourceManager.GetString("PlayerControl_StreamlistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string PlayerControl_TryAgainButton {
            get {
                return ResourceManager.GetString("PlayerControl_TryAgainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QualityControls_Title {
            get {
                return ResourceManager.GetString("QualityControls_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string RadioChannelsControl_MemberError_LogoutButton {
            get {
                return ResourceManager.GetString("RadioChannelsControl_MemberError_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error. Please re-login.
        /// </summary>
        public static string RadioChannelsControl_MemberError_Text {
            get {
                return ResourceManager.GetString("RadioChannelsControl_MemberError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string RadioChannelsControl_MemberError_TryAgain {
            get {
                return ResourceManager.GetString("RadioChannelsControl_MemberError_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error. Check your connection and try again.
        /// </summary>
        public static string RadioChannelsControl_NoInternet {
            get {
                return ResourceManager.GetString("RadioChannelsControl_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string RadioChannelsControl_NoInternetButtonText {
            get {
                return ResourceManager.GetString("RadioChannelsControl_NoInternetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rock_back {
            get {
                object obj = ResourceManager.GetObject("rock_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rock_text {
            get {
                object obj = ResourceManager.GetObject("rock_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsControl_SaveButton {
            get {
                return ResourceManager.GetString("SettingsControl_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tunes_back {
            get {
                object obj = ResourceManager.GetObject("tunes_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tunes_text {
            get {
                object obj = ResourceManager.GetObject("tunes_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged as .
        /// </summary>
        public static string UserSettingsControl_LoginInfo {
            get {
                return ResourceManager.GetString("UserSettingsControl_LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string UserSettingsControl_LogoutButton {
            get {
                return ResourceManager.GetString("UserSettingsControl_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserSettingsControl_Title {
            get {
                return ResourceManager.GetString("UserSettingsControl_Title", resourceCulture);
            }
        }
    }
}
